#!/bin/bash
# BSPWM Colors - Auto-generated by wallust

bspc config normal_border_color "{{color0}}"
bspc config active_border_color "{{color2}}"
bspc config focused_border_color "{{color4}}"
bspc config presel_feedback_color "{{color1}}"
