-- Neovim Colors - Generated by wallust

vim.cmd('hi clear')
if vim.fn.exists('syntax_on') then vim.cmd('syntax reset') end
vim.o.background = 'dark'
vim.g.colors_name = 'wallust'

local c = {
    bg = '#252628',
    fg = '#F8F7F8',
    c0 = '#515254',
    c1 = '#895D67',
    c2 = '#7A90AE',
    c3 = '#CA7573',
    c4 = '#6D90B7',
    c5 = '#E7E8EC',
    c6 = '#EBE7EA',
    c7 = '#EDEBEC',
    c8 = '#A6A4A5',
}

local function hi(g, o)
    local cmd = 'hi ' .. g
    if o.fg then cmd = cmd .. ' guifg=' .. o.fg end
    if o.bg then cmd = cmd .. ' guibg=' .. o.bg end
    if o.gui then cmd = cmd .. ' gui=' .. o.gui end
    vim.cmd(cmd)
end

-- UI Elements
hi('Normal', { fg = c.fg, bg = c.bg })
hi('LineNr', { fg = c.c8 })
hi('CursorLine', { bg = c.c0 })
hi('CursorLineNr', { fg = c.c4, gui = 'bold' })
hi('Visual', { bg = c.c8 })
hi('Search', { fg = c.bg, bg = c.c3 })
hi('IncSearch', { fg = c.bg, bg = c.c4 })
hi('StatusLine', { fg = c.fg, bg = c.c0 })
hi('VertSplit', { fg = c.c8, bg = c.bg })
hi('Pmenu', { fg = c.fg, bg = c.c0 })
hi('PmenuSel', { fg = c.bg, bg = c.c4 })

-- Syntax
hi('Comment', { fg = c.c8, gui = 'italic' })
hi('Constant', { fg = c.c1 })
hi('String', { fg = c.c2 })
hi('Number', { fg = c.c3 })
hi('Function', { fg = c.c4 })
hi('Statement', { fg = c.c5, gui = 'bold' })
hi('Operator', { fg = c.c6 })
hi('Type', { fg = c.c3, gui = 'bold' })
hi('Error', { fg = c.c1, bg = c.bg })
hi('Todo', { fg = c.c3, bg = c.bg, gui = 'bold' })
hi('Directory', { fg = c.c4 })
hi('Title', { fg = c.c4, gui = 'bold' })
