#!/bin/sh
# BSPWM Colors - Generated by wallust

color0="#515254"
color1="#895D67"
color2="#7A90AE"
color3="#CA7573"
color4="#6D90B7"
color5="#E7E8EC"
color6="#EBE7EA"
color7="#EDEBEC"
color8="#A6A4A5"
background="#252628"
foreground="#F8F7F8"
